/**
 * Comunas de Chile organizadas por código de región.
 * Fuente: División Político-Administrativa de Chile (INE).
 */
export const COMUNAS_POR_REGION = {
  arica_y_parinacota: [
    'Arica', 'Camarones', 'Putre', 'General Lagos',
  ],
  tarapaca: [
    'Iquique', 'Alto Hospicio', 'Pozo Almonte', 'Camiña',
    'Colchane', 'Huara', 'Pica',
  ],
  antofagasta: [
    'Antofagasta', 'Mejillones', 'Sierra Gorda', 'Taltal',
    'Calama', 'Ollagüe', 'San Pedro de Atacama',
    'Tocopilla', 'María Elena',
  ],
  atacama: [
    'Copiapó', 'Caldera', 'Tierra Amarilla', 'Chañaral',
    'Diego de Almagro', 'Vallenar', 'Alto del Carmen',
    'Freirina', 'Huasco',
  ],
  coquimbo: [
    'La Serena', 'Coquimbo', 'Andacollo', 'La Higuera',
    'Paiguano', 'Vicuña', 'Illapel', 'Canela',
    'Los Vilos', 'Salamanca', 'Ovalle', 'Combarbalá',
    'Monte Patria', 'Punitaqui', 'Río Hurtado',
  ],
  valparaiso: [
    'Valparaíso', 'Casablanca', 'Concón', 'Juan Fernández',
    'Puchuncaví', 'Quintero', 'Viña del Mar', 'Isla de Pascua',
    'Los Andes', 'Calle Larga', 'Rinconada', 'San Esteban',
    'La Ligua', 'Cabildo', 'Papudo', 'Petorca', 'Zapallar',
    'Quillota', 'Calera', 'Hijuelas', 'La Cruz', 'Nogales',
    'San Antonio', 'Algarrobo', 'Cartagena', 'El Quisco',
    'El Tabo', 'Santo Domingo', 'San Felipe', 'Catemu',
    'Llay-Llay', 'Panquehue', 'Putaendo', 'Santa María',
    'Quilpué', 'Limache', 'Olmué', 'Villa Alemana',
  ],
  metropolitana: [
    'Alhué', 'Buin', 'Calera de Tango', 'Cerrillos',
    'Cerro Navia', 'Colina', 'Conchalí', 'Curacaví',
    'El Bosque', 'El Monte', 'Estación Central', 'Huechuraba',
    'Independencia', 'Isla de Maipo', 'La Cisterna', 'La Florida',
    'La Granja', 'La Pintana', 'La Reina', 'Lampa',
    'Las Condes', 'Lo Barnechea', 'Lo Espejo', 'Lo Prado',
    'Macul', 'Maipú', 'María Pinto', 'Melipilla',
    'Ñuñoa', 'Padre Hurtado', 'Paine', 'Pedro Aguirre Cerda',
    'Peñaflor', 'Peñalolén', 'Pirque', 'Providencia',
    'Pudahuel', 'Puente Alto', 'Quilicura', 'Quinta Normal',
    'Recoleta', 'Renca', 'San Bernardo', 'San Joaquín',
    'San José de Maipo', 'San Miguel', 'San Pedro', 'San Ramón',
    'Santiago', 'Talagante', 'Tiltil', 'Vitacura',
  ],
  ohiggins: [
    'Chépica', 'Chimbarongo', 'Codegua', 'Coinco',
    'Coltauco', 'Doñihue', 'Graneros', 'La Estrella',
    'Las Cabras', 'Litueche', 'Lolol', 'Machalí',
    'Malloa', 'Marchihue', 'Mostazal', 'Nancagua',
    'Navidad', 'Olivar', 'Palmilla', 'Paredones',
    'Peralillo', 'Peumo', 'Pichidegua', 'Pichilemu',
    'Placilla', 'Pumanque', 'Quinta de Tilcoco', 'Rancagua',
    'Rengo', 'Requínoa', 'San Fernando', 'San Vicente',
    'Santa Cruz',
  ],
  maule: [
    'Cauquenes', 'Chanco', 'Colbún', 'Constitución',
    'Curepto', 'Curicó', 'Empedrado', 'Hualañé',
    'Licantén', 'Linares', 'Longaví', 'Maule',
    'Molina', 'Parral', 'Pelarco', 'Pelluhue',
    'Pencahue', 'Rauco', 'Retiro', 'Río Claro',
    'Romeral', 'Sagrada Familia', 'San Clemente', 'San Javier',
    'San Rafael', 'Talca', 'Teno', 'Vichuquén',
    'Villa Alegre', 'Yerbas Buenas',
  ],
  nuble: [
    'Bulnes', 'Chillán', 'Chillán Viejo', 'Cobquecura',
    'Coelemu', 'Coihueco', 'El Carmen', 'Ninhue',
    'Ñiquén', 'Pemuco', 'Pinto', 'Portezuelo',
    'Quillón', 'Quirihue', 'Ránquil', 'San Carlos',
    'San Fabián', 'San Ignacio', 'San Nicolás', 'Treguaco',
    'Yungay',
  ],
  biobio: [
    'Alto Biobío', 'Antuco', 'Arauco', 'Cabrero',
    'Cañete', 'Chiguayante', 'Concepción', 'Contulmo',
    'Coronel', 'Curanilahue', 'Florida', 'Hualpén',
    'Hualqui', 'Laja', 'Lebu', 'Los Álamos',
    'Los Ángeles', 'Lota', 'Mulchén', 'Nacimiento',
    'Negrete', 'Penco', 'Quilaco', 'Quilleco',
    'San Pedro de la Paz', 'San Rosendo', 'Santa Bárbara', 'Santa Juana',
    'Talcahuano', 'Tirúa', 'Tomé', 'Tucapel',
    'Yumbel',
  ],
  la_araucania: [
    'Angol', 'Carahue', 'Cholchol', 'Collipulli',
    'Cunco', 'Curacautín', 'Curarrehue', 'Ercilla',
    'Freire', 'Galvarino', 'Gorbea', 'Lautaro',
    'Loncoche', 'Lonquimay', 'Los Sauces', 'Lumaco',
    'Melipeuco', 'Nueva Imperial', 'Padre Las Casas', 'Perquenco',
    'Pitrufquén', 'Pucón', 'Purén', 'Renaico',
    'Saavedra', 'Temuco', 'Teodoro Schmidt', 'Toltén',
    'Traiguén', 'Victoria', 'Vilcún', 'Villarrica',
  ],
  los_rios: [
    'Corral', 'Futrono', 'La Unión', 'Lago Ranco',
    'Lanco', 'Los Lagos', 'Máfil', 'Mariquina',
    'Paillaco', 'Panguipulli', 'Río Bueno', 'Valdivia',
  ],
  los_lagos: [
    'Ancud', 'Calbuco', 'Castro', 'Chaitén',
    'Chonchi', 'Cochamó', 'Curaco de Vélez', 'Dalcahue',
    'Fresia', 'Frutillar', 'Futaleufú', 'Hualaihué',
    'Llanquihue', 'Los Muermos', 'Maullín', 'Osorno',
    'Palena', 'Puerto Montt', 'Puerto Octay', 'Puerto Varas',
    'Puqueldón', 'Purranque', 'Puyehue', 'Queilén',
    'Quellón', 'Quemchi', 'Quinchao', 'Río Negro',
    'San Juan de la Costa', 'San Pablo',
  ],
  aysen: [
    'Aysén', 'Chile Chico', 'Cisnes', 'Cochrane',
    'Coyhaique', 'Guaitecas', 'Lago Verde', "O'Higgins",
    'Río Ibáñez', 'Tortel',
  ],
  magallanes: [
    'Antártica', 'Cabo de Hornos', 'Laguna Blanca', 'Natales',
    'Porvenir', 'Primavera', 'Punta Arenas', 'Río Verde',
    'San Gregorio', 'Timaukel', 'Torres del Paine',
  ],
}
