# Generated by Django 5.2.6 on 2026-05-07 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g_de_flota', '0002_documento_tipo_vehiculo_activo_vehiculo_anio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='rol',
        ),
        migrations.AddField(
            model_name='usuario',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='g_de_flota.empresa'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('SUPERADMIN', 'Super Administrador'), ('ADMIN', 'Administrador'), ('CONDUCTOR', 'Conductor')], default='ADMIN', max_length=20),
        ),
    ]
