# Generated by Django 5.2.6 on 2026-05-07 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g_de_flota', '0004_usuario_intentos_fallidos_usuario_is_blocked_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sistema', models.CharField(default='Gestión de Flota', max_length=255)),
                ('email_soporte', models.EmailField(default='soporte@empresa.com', max_length=254)),
                ('logo', models.TextField(blank=True, null=True)),
                ('tiempo_expiracion_sesion', models.IntegerField(default=60)),
                ('politica_pass_mayuscula', models.BooleanField(default=True)),
                ('politica_pass_numero', models.BooleanField(default=True)),
                ('politica_pass_min_length', models.IntegerField(default=8)),
            ],
            options={
                'verbose_name': 'Configuración Global',
                'verbose_name_plural': 'Configuración Global',
            },
        ),
        migrations.CreateModel(
            name='IPBloqueada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('motivo', models.CharField(max_length=255)),
                ('fecha_bloqueo', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'IP Bloqueada',
                'verbose_name_plural': 'IPs Bloqueadas',
            },
        ),
        migrations.CreateModel(
            name='PlanSuscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('basico', 'Básico'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], max_length=20, unique=True)),
                ('max_flotas', models.IntegerField(default=1)),
                ('max_vehiculos', models.IntegerField(default=10)),
                ('max_conductores', models.IntegerField(default=10)),
            ],
            options={
                'verbose_name': 'Plan de Suscripción',
                'verbose_name_plural': 'Planes de Suscripción',
            },
        ),
        migrations.CreateModel(
            name='PlantillaCorreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('bienvenida', 'Bienvenida'), ('reset_pass', 'Recuperar Contraseña'), ('notificacion_vencimiento', 'Notificación de Vencimiento')], max_length=50, unique=True)),
                ('asunto', models.CharField(max_length=255)),
                ('cuerpo_html', models.TextField()),
            ],
            options={
                'verbose_name': 'Plantilla de Correo',
                'verbose_name_plural': 'Plantillas de Correo',
            },
        ),
        migrations.AddField(
            model_name='empresa',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas', to='g_de_flota.plansuscripcion'),
        ),
    ]
