# Generated by Django 5.2.6 on 2026-05-08 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g_de_flota', '0008_empresa_campos_extendidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='hasta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='permiso',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='DocumentoConductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('licencia_conducir', 'Licencia de Conducir'), ('certificado_salud', 'Certificado de Salud'), ('antecedentes', 'Antecedentes'), ('otro', 'Otro')], default='otro', max_length=30)),
                ('numero', models.CharField(blank=True, default='', max_length=100)),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('vigente', 'Vigente'), ('por_vencer', 'Por vencer'), ('vencido', 'Vencido')], default='vigente', max_length=20)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='g_de_flota.perfilusuario')),
            ],
            options={
                'verbose_name': 'Documento del Conductor',
                'verbose_name_plural': 'Documentos de Conductores',
                'ordering': ['fecha_vencimiento'],
            },
        ),
    ]
