# Generated by Django 5.2.6 on 2026-05-11 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('g_de_flota', '0011_transfer_perfil_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentoconductor',
            name='perfil',
        ),
    ]
