# Generated by Django 5.2.6 on 2026-05-11 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('g_de_flota', '0012_remove_documentoconductor_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacion',
            name='perfil',
        ),
        migrations.DeleteModel(
            name='PerfilUsuario',
        ),
    ]
