# Generated by Django 5.2.6 on 2026-05-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g_de_flota', '0013_remove_asignacion_perfil_delete_perfilusuario'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='asignacion',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('vehiculo',), name='unique_active_vehicle_assignment'),
        ),
        migrations.AddConstraint(
            model_name='asignacion',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('conductor',), name='unique_active_conductor_assignment'),
        ),
    ]
