# Generated by Django 5.2.6 on 2026-05-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g_de_flota', '0014_asignacion_unique_active_vehicle_assignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantencion',
            name='kilometraje_programado',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mantencion',
            name='kilometraje_realizado',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mantencion',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='mantencion',
            name='fecha_programada',
            field=models.DateField(blank=True, null=True),
        ),
    ]
