# Generated by Django 5.2.6 on 2026-05-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g_de_flota', '0015_mantencion_kilometraje_programado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantencion',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='mantencion',
            name='presupuesto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='mantencion',
            name='taller_proveedor',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='mantencion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=50),
        ),
    ]
