# Generated by Django 5.2.6 on 2026-05-13 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g_de_flota', '0017_assign_mantenciones_permisos'),
    ]

    operations = [
        migrations.CreateModel(
            name='MantencionProgramada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ultima', models.DateField()),
                ('fecha_siguiente', models.DateField()),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva')], default='activa', max_length=20)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenciones_programadas', to='g_de_flota.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='AlertaMantencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('por_vencer', 'Por vencer'), ('vencida', 'Vencida')], max_length=20)),
                ('dias_restantes', models.IntegerField()),
                ('pct_avance', models.FloatField()),
                ('enviada', models.BooleanField(default=False)),
                ('atendida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_atencion', models.DateTimeField(blank=True, null=True)),
                ('mantencion_programada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='g_de_flota.mantencionprogramada')),
            ],
        ),
        migrations.CreateModel(
            name='PlanMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_mantenimiento', to='g_de_flota.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='ReglaMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('prioridad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=20)),
                ('intervalo_dias', models.IntegerField()),
                ('umbral_alerta_dias', models.IntegerField()),
                ('canal', models.CharField(choices=[('email', 'Email'), ('push', 'Push'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS')], default='email', max_length=20)),
                ('escalar_sin_respuesta', models.BooleanField(default=False)),
                ('bloquear_despacho', models.BooleanField(default=False)),
                ('costo_estimado', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas', to='g_de_flota.planmantenimiento')),
            ],
        ),
        migrations.AddField(
            model_name='mantencionprogramada',
            name='regla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenciones_programadas', to='g_de_flota.reglamantenimiento'),
        ),
        migrations.CreateModel(
            name='VehiculoPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos_asignados', to='g_de_flota.planmantenimiento')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_asignados', to='g_de_flota.vehiculo')),
            ],
            options={
                'unique_together': {('vehiculo', 'plan')},
            },
        ),
    ]
