# Generated by Django 5.2.6 on 2026-05-14 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g_de_flota', '0018_mantencionprogramada_alertamantencion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='notif_prefs',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('mantencion_por_vencer', 'Mantención por vencer'), ('mantencion_vencida', 'Mantención vencida'), ('documento_por_vencer', 'Documento por vencer'), ('documento_vencido', 'Documento vencido'), ('seguridad', 'Seguridad'), ('actividad', 'Actividad')], max_length=30)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('url_accion', models.CharField(blank=True, default='', max_length=300)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha'],
            },
        ),
    ]
