# Generated by Django 5.2.6 on 2026-05-17 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g_de_flota', '0021_plan_suscripcion_upgrade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plansuscripcion',
            options={'ordering': ['orden', 'id'], 'verbose_name': 'Plan de Suscripción', 'verbose_name_plural': 'Planes de Suscripción'},
        ),
        migrations.AddField(
            model_name='usuario',
            name='politicas_aceptadas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='primer_login',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('mantencion_por_vencer', 'Mantención por vencer'), ('mantencion_vencida', 'Mantención vencida'), ('documento_por_vencer', 'Documento por vencer'), ('documento_vencido', 'Documento vencido'), ('seguridad', 'Seguridad'), ('actividad', 'Actividad'), ('limite_plan', 'Límite de plan')], max_length=30),
        ),
        migrations.AlterField(
            model_name='plansuscripcion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
