# Generated by Django 5.2.6 on 2026-05-18 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g_de_flota', '0022_usuario_politicas_primer_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='plansuscripcion',
            name='permisos',
            field=models.ManyToManyField(blank=True, related_name='planes', to='g_de_flota.permiso'),
        ),
    ]
