# Generated by Django 5.2.6 on 2026-05-18 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g_de_flota', '0023_plan_permisos_m2m'),
    ]

    operations = [
        migrations.CreateModel(
            name='GastoOperativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('combustible', 'Combustible'), ('mantencion', 'Mantención'), ('multa', 'Multa'), ('peaje', 'Peaje'), ('seguro', 'Seguro'), ('otro', 'Otro')], max_length=20)),
                ('descripcion', models.CharField(max_length=300)),
                ('monto', models.DecimalField(decimal_places=0, max_digits=10)),
                ('fecha', models.DateField()),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='comprobantes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conductor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos_conductor', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='g_de_flota.empresa')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos_registrados', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='g_de_flota.vehiculo')),
            ],
            options={
                'verbose_name': 'Gasto operativo',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PresupuestoMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveSmallIntegerField()),
                ('mes', models.PositiveSmallIntegerField()),
                ('monto', models.DecimalField(decimal_places=0, max_digits=12)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos', to='g_de_flota.empresa')),
            ],
            options={
                'verbose_name': 'Presupuesto mensual',
                'unique_together': {('empresa', 'anio', 'mes')},
            },
        ),
    ]
