# Generated by Django 5.2.6 on 2026-05-18 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g_de_flota', '0025_finanzas_permisos'),
    ]

    operations = [
        # ── Limpieza previa ──────────────────────────────────────────────────
        # Los modelos antiguos DocumentoVehiculo (renombrado desde 'Documento'
        # en 0010) y DocumentoConductor se eliminan ANTES de crear el nuevo
        # 'Documento'. Esto es imprescindible en PostgreSQL: al renombrar la
        # tabla en 0010, el índice del FK conservó su nombre original
        # (g_de_flota_documento_vehiculo_id_196fd87b). Si se creara el nuevo
        # Documento sin liberar antes ese nombre, PostgreSQL aborta con
        # "relation ... already exists". Borrando primero el modelo viejo se
        # libera el índice y el CreateModel siguiente corre en limpio.
        migrations.RemoveField(
            model_name='documentovehiculo',
            name='vehiculo',
        ),
        migrations.DeleteModel(
            name='DocumentoConductor',
        ),
        migrations.DeleteModel(
            name='DocumentoVehiculo',
        ),

        # ── Modelo Documento (unificado vehículo + conductor) ────────────────
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad', models.CharField(choices=[('vehiculo', 'Vehículo'), ('conductor', 'Conductor')], max_length=20)),
                ('tipo', models.CharField(choices=[('permiso_circulacion', 'Permiso de circulación'), ('revision_tecnica', 'Revisión técnica'), ('seguro_soap', 'Seguro SOAP'), ('licencia', 'Licencia de conducir'), ('antecedentes', 'Antecedentes comerciales')], max_length=30)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='documentos/%Y/%m/')),
                ('nombre_archivo', models.CharField(blank=True, default='', max_length=200)),
                ('notas', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conductor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docs_c', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='g_de_flota.empresa')),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docs_subidos', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docs_v', to='g_de_flota.vehiculo')),
                ('version_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versiones_nuevas', to='g_de_flota.documento')),
            ],
            options={
                'verbose_name': 'Documento',
                'ordering': ['-created_at'],
            },
        ),
    ]
