# Generated by Django 5.2.6 on 2026-05-19 22:51

from django.db import migrations


class Migration(migrations.Migration):
    """
    Migración intencionalmente vacía.

    Sus operaciones originales (eliminar DocumentoVehiculo y DocumentoConductor)
    se movieron al INICIO de la 0026 para que el modelo viejo se borre ANTES de
    crear el nuevo 'Documento'. Así se libera el índice del FK en PostgreSQL y se
    evita el error "relation ... already exists". Se conserva el archivo para no
    romper la cadena de dependencias de las migraciones siguientes.
    """

    dependencies = [
        ('g_de_flota', '0026_documento'),
    ]

    operations = []
