# Generated by Django 5.2.6 on 2026-05-19 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('g_de_flota', '0026_documento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentovehiculo',
            name='vehiculo',
        ),
        migrations.DeleteModel(
            name='DocumentoConductor',
        ),
        migrations.DeleteModel(
            name='DocumentoVehiculo',
        ),
    ]
