# Generated by Django 5.2.6 on 2026-05-20 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g_de_flota', '0027_remove_documento_base_conductor_vehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='consumo_l_100km',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
        migrations.CreateModel(
            name='ConfiguracionRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_bencina', models.IntegerField(default=1380)),
                ('precio_diesel', models.IntegerField(default=1250)),
                ('radio_deteccion_peaje', models.IntegerField(default=500, help_text='Radio en metros')),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_ruta', to='g_de_flota.empresa')),
            ],
            options={
                'verbose_name': 'Configuración de Ruta',
            },
        ),
        migrations.CreateModel(
            name='Peaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('ruta', models.CharField(max_length=100)),
                ('autopista', models.CharField(blank=True, default='', max_length=200)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('categoria', models.CharField(choices=[('liviano', 'Liviano'), ('camion2', 'Camión 2 ejes'), ('camion3', 'Camión 3+ ejes'), ('bus', 'Bus'), ('moto', 'Moto')], default='liviano', max_length=20)),
                ('tarifa_normal', models.DecimalField(decimal_places=0, max_digits=8)),
                ('tarifa_punta', models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Peaje',
                'verbose_name_plural': 'Peajes',
                'ordering': ['ruta', 'nombre'],
                'unique_together': {('nombre', 'ruta', 'categoria')},
            },
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('carga', 'Carga'), ('personas', 'Personas')], default='carga', max_length=20)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('pendiente', 'Pendiente'), ('activo', 'Activo'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('fecha_programada', models.DateField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('km_inicio', models.IntegerField(blank=True, null=True)),
                ('km_fin', models.IntegerField(blank=True, null=True)),
                ('distancia_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('duracion_min', models.IntegerField(blank=True, null=True)),
                ('costo_combustible_est', models.IntegerField(default=0)),
                ('costo_peajes_est', models.IntegerField(default=0)),
                ('costo_total_est', models.IntegerField(default=0)),
                ('costo_combustible_real', models.IntegerField(blank=True, null=True)),
                ('costo_peajes_real', models.IntegerField(blank=True, null=True)),
                ('costo_total_real', models.IntegerField(blank=True, null=True)),
                ('polyline', models.JSONField(blank=True, default=list)),
                ('notas', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conductor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutas_conductor', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas', to='g_de_flota.empresa')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutas', to='g_de_flota.vehiculo')),
            ],
            options={
                'verbose_name': 'Ruta',
                'verbose_name_plural': 'Rutas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('origen', 'Origen'), ('parada', 'Parada'), ('destino', 'Destino')], default='parada', max_length=20)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(blank=True, default='', max_length=400)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('notas', models.CharField(blank=True, default='', max_length=400)),
                ('hora_estimada', models.DateTimeField(blank=True, null=True)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas', to='g_de_flota.ruta')),
            ],
            options={
                'verbose_name': 'Parada',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='PeajeRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarifa', models.DecimalField(decimal_places=0, max_digits=8)),
                ('peaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutaspeaje', to='g_de_flota.peaje')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peajesruta', to='g_de_flota.ruta')),
            ],
            options={
                'verbose_name': 'Peaje de Ruta',
                'unique_together': {('ruta', 'peaje')},
            },
        ),
    ]
