# Generated by Django 5.2.6 on 2026-05-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g_de_flota', '0042_solicitudes_permisos_por_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantencion',
            name='confirmado_conductor',
            field=models.BooleanField(default=False, help_text='True cuando el conductor acepta el servicio y el precio final.', verbose_name='Confirmado por conductor'),
        ),
        migrations.AddField(
            model_name='mantencion',
            name='fecha_confirmacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de confirmación'),
        ),
        migrations.AddField(
            model_name='mantencion',
            name='foto_comprobante',
            field=models.ImageField(blank=True, help_text='Foto del recibo o trabajo realizado, subida al completar la mantención.', null=True, upload_to='mantenciones/comprobantes/', verbose_name='Foto comprobante'),
        ),
    ]
