# Generated by Django 5.2.6 on 2026-05-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g_de_flota', '0043_confirmacion_mantencion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='extra',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='solicitudconductor',
            name='extra',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
