# Generated by Django 5.2.6 on 2026-05-27 17:32

from django.db import migrations, models


def trial_a_pendiente(apps, schema_editor):
    """Convierte suscripciones en estado 'trial' a 'pendiente'."""
    Suscripcion = apps.get_model('g_de_flota', 'Suscripcion')
    Suscripcion.objects.filter(estado='trial').update(estado='pendiente')


class Migration(migrations.Migration):

    dependencies = [
        ('g_de_flota', '0051_configuracionsistema_dias_trial'),
    ]

    operations = [
        # 1. Convertir datos antes de cambiar el campo
        migrations.RunPython(trial_a_pendiente, migrations.RunPython.noop),
        # 2. Eliminar campo trial_hasta
        migrations.RemoveField(
            model_name='suscripcion',
            name='trial_hasta',
        ),
        migrations.AlterField(
            model_name='eventoruta',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        # 3. Actualizar choices del campo estado
        migrations.AlterField(
            model_name='suscripcion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de pago'), ('activa', 'Activa'), ('gracia', 'Período de gracia'), ('suspendida', 'Suspendida'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20),
        ),
    ]
