# Generated by Django 5.2.6 on 2026-05-27 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g_de_flota', '0053_corregir_activas_sin_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='email_activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='email_from_address',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='email_from_name',
            field=models.CharField(blank=True, default='FlotaSystem', max_length=200),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='email_host',
            field=models.CharField(blank=True, default='smtp.gmail.com', max_length=200),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='email_host_password',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='email_host_user',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='email_port',
            field=models.PositiveIntegerField(default=587),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='email_use_ssl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='email_use_tls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='notif_bienvenida',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='notif_checklist_fallas',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='notif_documento_vence',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='notif_mantencion_vence',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='notif_pago_aprobado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='notif_pago_rechazado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='notif_ruta_asignada',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='notif_solicitud_nueva',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='notif_solicitud_resuelta',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='notif_suscripcion_bloqueada',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='notif_suscripcion_gracia',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='notif_suscripcion_vence',
            field=models.BooleanField(default=True),
        ),
    ]
