# Generated by Django 5.2.6 on 2026-05-27 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('g_de_flota', '0054_email_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracionsistema',
            name='dias_trial',
        ),
    ]
