# Generated by Django 5.2.6 on 2026-05-28 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g_de_flota', '0057_remove_email_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='apellido_materno_cifrado',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='apellido_paterno_cifrado',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='primer_nombre_cifrado',
            field=models.TextField(blank=True, null=True),
        ),
    ]
