# Generated by Django 5.2.6 on 2026-05-29 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g_de_flota', '0060_alter_empresa_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plansuscripcion',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
