# Generated by Django 5.2.6 on 2026-05-29 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g_de_flota', '0061_alter_plansuscripcion_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plansuscripcion',
            name='precio_anual',
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='ciclo',
            field=models.CharField(choices=[('mensual', 'Mensual')], default='mensual', max_length=10),
        ),
    ]
