# Generated by Django 5.2.6 on 2026-05-29 05:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g_de_flota', '0062_remove_plansuscripcion_precio_anual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plansuscripcion',
            name='descripcion',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='plansuscripcion',
            name='nombre',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='plansuscripcion',
            name='precio_mensual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
