# Generated by Django 5.2.6 on 2026-05-29 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('g_de_flota', '0064_ubicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ubicacion',
            name='combustible',
        ),
    ]
