# Generated by Django 5.2.6 on 2026-05-29 23:16

import g_de_flota.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('g_de_flota', '0065_remove_ubicacion_combustible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoruta',
            name='texto',
            field=g_de_flota.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='gastooperativo',
            name='descripcion',
            field=g_de_flota.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name='mantencion',
            name='descripcion',
            field=g_de_flota.fields.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='mantencion',
            name='taller_proveedor',
            field=g_de_flota.fields.EncryptedCharField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='mantencion',
            name='tipo_mantencion',
            field=g_de_flota.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='mensaje',
            field=g_de_flota.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='titulo',
            field=g_de_flota.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name='parada',
            name='direccion',
            field=g_de_flota.fields.EncryptedCharField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='parada',
            name='latitud',
            field=g_de_flota.fields.EncryptedFloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parada',
            name='longitud',
            field=g_de_flota.fields.EncryptedFloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parada',
            name='nombre',
            field=g_de_flota.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name='parada',
            name='notas',
            field=g_de_flota.fields.EncryptedCharField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='descripcion',
            field=g_de_flota.fields.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='nombre',
            field=g_de_flota.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='notas',
            field=g_de_flota.fields.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='solicitudconductor',
            name='descripcion',
            field=g_de_flota.fields.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='solicitudconductor',
            name='respuesta',
            field=g_de_flota.fields.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='solicitudconductor',
            name='titulo',
            field=g_de_flota.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='latitud',
            field=g_de_flota.fields.EncryptedFloatField(),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='longitud',
            field=g_de_flota.fields.EncryptedFloatField(),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='velocidad',
            field=g_de_flota.fields.EncryptedFloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=g_de_flota.fields.EncryptedCharField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='modelo',
            field=g_de_flota.fields.EncryptedCharField(blank=True, default=''),
        ),
    ]
