# Generated by Django 5.2.6 on 2026-05-29 23:40

import g_de_flota.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g_de_flota', '0067_cifrar_datos_existentes'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='patente_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='patente',
            field=g_de_flota.fields.EncryptedCharField(),
        ),
    ]
