# Generated by Django 5.2.6 on 2026-05-29 23:47

import g_de_flota.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g_de_flota', '0069_cifrar_patentes'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=g_de_flota.fields.EncryptedCharField(),
        ),
    ]
