# Generated by Django 5.2.6 on 2026-06-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g_de_flota', '0074_eliminar_permisos_geo_gantt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='rut_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
    ]
