# Generated by Django 5.2.6 on 2026-06-02 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g_de_flota', '0075_alter_empresa_rut_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionGPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servidor_ip', models.CharField(blank=True, default='', max_length=50)),
                ('servidor_puerto', models.IntegerField(default=5000)),
                ('protocolo', models.CharField(choices=[('tcp', 'TCP'), ('udp', 'UDP')], default='tcp', max_length=3)),
                ('activo', models.BooleanField(default=True)),
                ('actualizado_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_gps', to='g_de_flota.empresa')),
            ],
            options={
                'verbose_name': 'Configuración GPS',
                'verbose_name_plural': 'Configuraciones GPS',
            },
        ),
        migrations.CreateModel(
            name='DispositivoGPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=20, unique=True)),
                ('modelo', models.CharField(choices=[('emulador', 'Emulador NMEA'), ('teltonika_fmb920', 'Teltonika FMB920'), ('teltonika_fmc125', 'Teltonika FMC125'), ('queclink_gl300', 'Queclink GL300'), ('coban_tk103', 'Coban TK103'), ('otro', 'Otro')], default='emulador', max_length=30)),
                ('api_key', models.CharField(blank=True, default='', max_length=64)),
                ('activo', models.BooleanField(default=True)),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos_gps', to='g_de_flota.empresa')),
                ('vehiculo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispositivo_gps', to='g_de_flota.vehiculo')),
            ],
            options={
                'verbose_name': 'Dispositivo GPS',
                'verbose_name_plural': 'Dispositivos GPS',
                'ordering': ['-creado_at'],
            },
        ),
    ]
