# Generated by Django 5.2.6 on 2026-06-03 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('g_de_flota', '0078_dispositivogps_modelo_otro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfiguracionGPS',
        ),
    ]
