# Generated by Django 5.2.6 on 2026-06-04 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('g_de_flota', '0080_vehiculo_empresa_directa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plansuscripcion',
            name='max_flotas',
        ),
    ]
