# Generated by Django 5.2.6 on 2026-06-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g_de_flota', '0081_remove_plansuscripcion_max_flotas'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ubicacion',
            index=models.Index(fields=['vehiculo', '-timestamp'], name='ubicacion_veh_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='ubicacion',
            index=models.Index(fields=['timestamp'], name='ubicacion_ts_idx'),
        ),
    ]
