# Generated by Django 5.2.6 on 2026-06-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g_de_flota', '0082_ubicacion_ubicacion_veh_ts_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastooperativo',
            name='categoria_correctiva',
            field=models.CharField(blank=True, choices=[('falla_mecanica', 'Falla mecánica urgente'), ('repuesto_urgente', 'Repuesto no planificado'), ('accidente', 'Daño por accidente'), ('electrico', 'Falla eléctrica'), ('neumatico', 'Neumático de emergencia'), ('otro_correctivo', 'Otro correctivo')], default='', help_text='Solo si es_correctivo=True.', max_length=30),
        ),
        migrations.AddField(
            model_name='gastooperativo',
            name='es_correctivo',
            field=models.BooleanField(default=False, help_text='True si es un gasto correctivo no presupuestado (falla inesperada).'),
        ),
        migrations.AddField(
            model_name='gastooperativo',
            name='prioridad_correctiva',
            field=models.CharField(blank=True, choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='', help_text='Solo si es_correctivo=True.', max_length=10),
        ),
    ]
