# Generated by Django 5.2.6 on 2026-06-04 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g_de_flota', '0084_correctivos_permisos'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscripcion',
            name='fecha_cambio_programado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='plan_programado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suscripciones_programadas', to='g_de_flota.plansuscripcion'),
        ),
    ]
