# Generated by Django 5.2.6 on 2026-06-04 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g_de_flota', '0086_eliminar_permisos_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagotransbank',
            name='iniciado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_iniciados', to=settings.AUTH_USER_MODEL),
        ),
    ]
