# Generated by Django 5.2.6 on 2026-06-05 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g_de_flota', '0089_eliminar_finanzas_exportar'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='vehiculos/fotos/'),
        ),
    ]
