# Generated by Django 5.2.6 on 2026-06-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g_de_flota', '0090_vehiculo_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantencion',
            name='es_correctivo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mantencion',
            name='gasto_correctivo_generado',
            field=models.BooleanField(default=False),
        ),
    ]
