# Generated by Django 5.2.6 on 2026-06-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g_de_flota', '0093_aviso_destino_todas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aviso',
            name='destino',
            field=models.CharField(choices=[('flota', 'Toda la flota'), ('conductor', 'Conductor específico'), ('admins', 'Administradores'), ('todas', 'Todas las empresas'), ('superadmin', 'Superadmin')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('mantencion_por_vencer', 'Mantención por vencer'), ('mantencion_vencida', 'Mantención vencida'), ('documento_por_vencer', 'Documento por vencer'), ('documento_vencido', 'Documento vencido'), ('seguridad', 'Seguridad'), ('actividad', 'Actividad'), ('limite_plan', 'Límite de plan'), ('recordatorio_ruta', 'Recordatorio de ruta'), ('recordatorio_checklist', 'Recordatorio de checklist'), ('recordatorio_finalizar', 'Recordatorio de finalizar ruta'), ('recordatorio_vispera', 'Recordatorio de ruta del día siguiente'), ('recordatorio_documentos', 'Recordatorio de documentos'), ('checklist_completado', 'Checklist completado'), ('checklist_enviado', 'Checklist con fallas')], max_length=30),
        ),
    ]
